//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStatu
    {
        public int JobStatusID { get; set; }
        public Nullable<short> JobType { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
