//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseFile
    {
        public int ID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public byte[] FileContent { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
