//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordReset
    {
        public int PasswordResetID { get; set; }
        public string EmailID { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
