//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileID { get; set; }
        public int UserID { get; set; }
        public string AltEmail { get; set; }
        public bool BillingAddressSame { get; set; }
        public string BillingAddress { get; set; }
        public string BillingAddress_2 { get; set; }
        public string BillingCty { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<bool> SMSOpt { get; set; }
        public string PaymentMethod { get; set; }
        public string PaypalEmail { get; set; }
        public string PayoutMailAddress { get; set; }
        public string PayoutMailAddress2 { get; set; }
        public string PayoutMailCity { get; set; }
        public string PayoutMailState { get; set; }
        public string PayoutMailZip { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    
        public virtual User User { get; set; }
    }
}
