//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentPayment
    {
        public int RentPaymentID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> RentMon { get; set; }
        public Nullable<int> RentYear { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Property Property { get; set; }
    }
}
