//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentDue
    {
        public int RentDueID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> DueMon { get; set; }
        public Nullable<int> DueYear { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal DueAmount { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DueStatus { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
