//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int TenantID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public Nullable<System.DateTime> FinalDueDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<System.DateTime> DepostDueDate { get; set; }
        public bool PetDepositDue { get; set; }
        public Nullable<decimal> PetDeposit { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<System.DateTime> Deletedon { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
