//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.Profiles = new HashSet<Profile>();
            this.Properties = new HashSet<Property>();
            this.RentDues = new HashSet<RentDue>();
            this.Tenants = new HashSet<Tenant>();
            this.UserCCs = new HashSet<UserCC>();
            this.UserReferences = new HashSet<UserReference>();
            this.RentAutoPays = new HashSet<RentAutoPay>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public short UserType { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public Nullable<System.DateTime> Deletedon { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<RentDue> RentDues { get; set; }
        public virtual ICollection<Tenant> Tenants { get; set; }
        public virtual ICollection<UserCC> UserCCs { get; set; }
        public virtual ICollection<UserReference> UserReferences { get; set; }
        public virtual ICollection<RentAutoPay> RentAutoPays { get; set; }
    }
}
