//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCC
    {
        public int UserCCID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<short> PaymentType { get; set; }
        public string CCNO { get; set; }
        public string ExpMon { get; set; }
        public string ExpYear { get; set; }
        public string CVV { get; set; }
        public string AccountType { get; set; }
        public string RoutingNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
    
        public virtual User User { get; set; }
    }
}
