//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductOrder
    {
        public int ProductOrderID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public string TransId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string CustomerFName { get; set; }
        public string CustomerLName { get; set; }
        public short UserType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Comments { get; set; }
        public int OrderID { get; set; }
    }
}
