//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRentPayment
    {
        public int ID { get; set; }
        public int PropertyID { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransID { get; set; }
        public int TenantUserID { get; set; }
        public string TenantFirstName { get; set; }
        public string TenantLastName { get; set; }
        public string StatusText { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public int OwnerUserID { get; set; }
    }
}
