//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGBC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public int ZipCodeID { get; set; }
        public Nullable<int> ZipCode1 { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    }
}
